name: Generate Snake Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        id: snake
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg?color_snake=%230A66C2&color_dots=%23ebedf0,%23bfdbfe,%2360a5fa,%232563eb,%230A66C2
            dist/snake-dark.svg?color_snake=%230A66C2&color_dots=%23161b22,%230a3069,%230f4c9c,%231f6feb,%2358a6ff

      - name: Publica no branch output
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
